In [2]:
!pip install numpy

In [3]:
import numpy as np
import time

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64


In [7]:
playlist=list(range(1_000_000))
py_result=[]
time_start=time.time()
for i in playlist:
    py_result.append(i+5)
time_end=time.time()
print("Python List time: ", time_end-time_start)

Python List time:  0.38018369674682617


In [10]:
np_array=np.arange(1_000_000)
time_start=time.time()
np_result=np_array+5
time_end=time.time()
print("NumPy array time: ", time_end-time_start)

NumPy array time:  0.005736589431762695


In [12]:
# NumPy array
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [16]:
print(np.zeros((2,3))) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(np.ones((2,3))) 

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
print(np.full((2,3), 7)) 

[[7 7 7]
 [7 7 7]]


In [21]:
print(np.arange(0, 10, 3))

[0 3 6 9]


In [26]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [30]:
print(np.eye(3)) # identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [32]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [34]:
arr=np.array([1.5, 2.7, 5.4])
print(arr.astype(int))

[1 2 5]


In [35]:
# NumPy Indexing, Slicing & Strides
arr=np.array([[10,20,30],
             [40,50,60],
             [70, 80, 90]])

In [37]:
print(arr[0,1])
print(arr[1,1])
print(arr[2,1])

20
50
80


In [40]:
print(arr[0,-1])
print(arr[-1,-1])
print(arr[-2,-3])

30
90
40


In [44]:
# general form arr[start:stop;step]
print(arr[0:2, 1:3])

[[20 30]
 [50 60]]


In [46]:
print(arr[::2, ::2])

[[10 30]
 [70 90]]


In [54]:
slice_arr=arr[0, :2] 
slice_arr[0]=999
print(slice_arr)

[999  20]


In [55]:
print(arr) # change value

[[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]


In [52]:
# if not want to change the value
copy_arr=arr[1].copy() 
copy_arr[0]=555
print(copy_arr)

[555  50  60]


In [53]:
print(arr) # not change value

[[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]


In [56]:
# NumPy Random Numbers, Reproducibility

In [66]:
# simulate 100k coin flips
rng=np.random.default_rng() # change mean
flips=rng.integers(0,2,size=100000) # 0=tails, 1=heads
prob_heads=np.mean(flips)
print("Estimated probability of heads: ", prob_heads)

Estimated probability of heads:  0.4983


In [67]:
# simulate 100k coin flips
rng=np.random.default_rng(seed=40) # fix mean, generate same seq of random numbers 
flips=rng.integers(0,2,size=100000) # 0=tails, 1=heads
prob_heads=np.mean(flips)
print("Estimated probability of heads: ", prob_heads)

Estimated probability of heads:  0.50125


In [65]:
# python loop
time_start=time.time()
squares=[i**2 for i in range(100000)]
time_end=time.time()
print("Loop time: ", time_end-time_start)

# numPy vectorized
time_start=time.time()
arr=np.arange(100000)
squares_np=arr**2
time_end=time.time()
print("Vectorized time: ", time_end-time_start)

Loop time:  0.022097349166870117
Vectorized time:  0.0058710575103759766
