In [1]:
# SVM implementation with Scikit-Learn
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix
)

In [2]:
# 1) Load dataset
data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

Training samples: 426
Test samples: 143


In [3]:
# 2) Train SVM with different kernels
models = {
    "Linear": SVC(kernel="linear", C=1.0),
    "RBF": SVC(kernel="rbf", C=1.0, gamma=0.01),
    "Poly": SVC(kernel="poly", degree=3, C=1.0)
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    results[name] = (acc, cm)

In [4]:
# 3) Print evaluation results
for name, (acc, cm) in results.items():
    print(f"\n=== {name} Kernel ===")
    print(f"Accuracy: {acc:.4f}")
    print("Confusion Matrix:")
    print(cm)


=== Linear Kernel ===
Accuracy: 0.9510
Confusion Matrix:
[[47  6]
 [ 1 89]]

=== RBF Kernel ===
Accuracy: 0.6294
Confusion Matrix:
[[ 0 53]
 [ 0 90]]

=== Poly Kernel ===
Accuracy: 0.9161
Confusion Matrix:
[[43 10]
 [ 2 88]]


In [5]:
# 4) Simple hyperparameter tuning (C)
best_acc = 0
best_C = None

for C in [0.1, 1, 10, 50]:
    svm = SVC(
        kernel="rbf",
        C=C,
        gamma=0.01
    )

    svm.fit(X_train, y_train)

    y_pred = svm.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    print(f"C={C:4}: Accuracy={acc:.4f}")

    if acc > best_acc:
        best_acc = acc
        best_C = C

print(f"\nBest C selected: {best_C}")

C= 0.1: Accuracy=0.6294
C=   1: Accuracy=0.6294
C=  10: Accuracy=0.6364
C=  50: Accuracy=0.6364

Best C selected: 10
